# Ref: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
# Runtime Versions: https://docs.aws.amazon.com/codebuild/latest/userguide/runtime-versions.html
version: 0.2
run-as: root
phases:
  install:
    runtime-versions:
      php: 8.0
      nodejs: 14
    commands:
      #- echo "Building from trigger -> $CODEBUILD_WEBHOOK_TRIGGER <- with dev dependencies"
      #- curl -s https://getcomposer.org/installer | php
      #- mv  composer.phar /usr/local/bin/composer
      # - php --version
      # - composer --version
      - composer install --no-interaction --prefer-dist --optimize-autoloader
      - cp .env.example .env
      - php artisan key:generate
  pre_build:
    commands:
      - php artisan test
      # - echo "Run php unit test"
      # - ./vendor/bin/phpunit
  build:
    commands:
      - echo "todo -> Build an artifact"
  post_build:
    commands:
      - echo "todo -> Kick off a deployment"
      - php artisan route:cache
      - php artisan view:cache
      - php artisan cache:clear
      - php artisan config:cache
artifacts:
  files:
    - "**/*"
  name: $CODEBUILD_RESOLVED_SOURCE_VERSION